[package]
name = "lan-mouse-egui"
description = "egui / eframe frontend for lan-mouse"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/zibo-chen/lan-mouse-egui"

[dependencies]
chrono = "0.4"
eframe = { version = "0.33.3", default-features = false, features = [
    "default_fonts",
    "glow",
    "wayland",
    "x11",
] }
egui-desktop = "0.2.5"
egui_extras = { version = "0.33.3", features = ["all_loaders"] }
hostname = "0.4.0"
lan-mouse-ipc = { path = "../lan-mouse-ipc", version = "0.2.0" }
log = "0.4.20"
thiserror = "2.0.0"
tray-icon = "0.21.3"
